version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: fooddelivery-rabbitmq
    ports:
      - "5672:5672"     # AMQP messaging port
      - "15672:15672"   # Management Dashboard UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  postgres:
    image: postgres:16-alpine
    container_name: fooddelivery-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgrespassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: